<?php
/**
 * Created by PhpStorm.
 * User: ari
 * Date: 3/9/2015
 * Time: 5:46 PM
 */
namespace CPath\Render\HTML\Exceptions;

use Exception;

class ElementNotFoundException extends \Exception
{
    public function __construct($message = "", $code = 0, Exception $previous = null) {
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }
}